front_left_foot:
  angle: 90
  multiplier: 1.0
front_left_leg:
  angle: 90
  multiplier: 1.0
front_left_shoulder:
  angle: 90
  multiplier: 1.0
front_right_foot:
  angle: 90
  multiplier: -1.0
front_right_leg:
  angle: 90
  multiplier: -1.0
front_right_shoulder:
  angle: 90
  multiplier: 1.0
rear_left_foot:
  angle: 90
  multiplier: 1.0
rear_left_leg:
  angle: 90
  multiplier: 1.0
rear_left_shoulder:
  angle: 90
  multiplier: -1.0
rear_right_foot:
  angle: 90
  multiplier: -1.0
rear_right_leg:
  angle: 90
  multiplier: -1.0
rear_right_shoulder:
  angle: 90
  multiplier: -1.0
