front_left_foot:
  angle: 171
  multiplier: 1.0
front_left_leg:
  angle: 104
  multiplier: 1.0
front_left_shoulder:
  angle: 78
  multiplier: 1.0
front_right_foot:
  angle: 36
  multiplier: -1.0
front_right_leg:
  angle: 109
  multiplier: -1.0
front_right_shoulder:
  angle: 78
  multiplier: 1.0
rear_left_foot:
  angle: 177
  multiplier: 1.0
rear_left_leg:
  angle: 104
  multiplier: 1.0
rear_left_shoulder:
  angle: 99
  multiplier: -1.0
rear_right_foot:
  angle: 24
  multiplier: -1.0
rear_right_leg:
  angle: 92
  multiplier: -1.0
rear_right_shoulder:
  angle: 139
  multiplier: -1.0
