front_left_foot:
  angle: 151
  multiplier: 1.0
front_left_leg:
  angle: 37
  multiplier: 1.0
front_left_shoulder:
  angle: 93
  multiplier: 1.0
front_right_foot:
  angle: 38
  multiplier: -1.0
front_right_leg:
  angle: 155
  multiplier: -1.0
front_right_shoulder:
  angle: 95
  multiplier: 1.0
rear_left_foot:
  angle: 154
  multiplier: 1.0
rear_left_leg:
  angle: 53
  multiplier: 1.0
rear_left_shoulder:
  angle: 90
  multiplier: -1.0
rear_right_foot:
  angle: 46
  multiplier: -1.0
rear_right_leg:
  angle: 157
  multiplier: -1.0
rear_right_shoulder:
  angle: 80
  multiplier: -1.0
